### ISSUE TITLE
Rename board to list

### ISSUE THREAD

**Issue by Zettt** [vesan/omnifocus-trello#10]
`omnifocus-trello` names lists "boards". This is confusing to me as user. The config says:

`:done_boards:`, but actually those aren't boards, those are lists. On Trello we have organization, board, list, card, and then a couple of things that are smaller like checklists and comments.

**Comment by vesan** [comment]
Thanks for the correction! Sorry this took so horribly long to do :-/

Released a new version with the change (https://rubygems.org/gems/omnifocus-trello/versions/1.2.2). It's backwards compatible so the old incorrect term still works in the `.omnifocus-trello.yml` file.

**Comment by Zettt** [comment]
Thanks, @vesan. Glad to see you're on it. :+1:
