### ISSUE TITLE
Sort organizations into folders

### ISSUE THREAD

**Issue by Zettt** [vesan/omnifocus-trello#11]
It would be great to have the ability to sort different organizations into folders. I'm working with about 4 to 5 clients and it's hard to keep track which OmniFocus project belongs to which organization since they're sorted alphabetically.

**Comment by vesan** [comment]
Unfortunately the project this plugin is using (https://github.com/seattlerb/omnifocus) doesn't support folders so the feature would need to be added there first before it could be implemented into the Trello integration.

**Comment by Zettt** [comment]
Thanks, I'll dupe it there.
